CSharp-DB/Databases-Advanced/Homeworks/WorkshopQuizSystem/Quiz.Web/Models/ErrorViewModel.cs
using System;

namespace Quiz.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSharp-DB/Databases-Advanced/Homeworks/WorkshopQuizSystem/Quiz.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Quiz.Services;
using Quiz.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Quiz.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IQuizService quizService;

        public HomeController(IQuizService quizService)
        {
            this.quizService = quizService;
        }

        public IActionResult Index()
        {
            var userName = this.User?.Identity?.Name;
            var userQuizes = this.quizService.GetQuizesByUserName(userName);
            return View(userQuizes);
        }

        public IActionResult Privacy()
        {
            Console.WriteLine("Hello from Privacy() in HomeController");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CSharp-DB/Databases-Advanced/Homeworks/WorkshopQuizSystem/Quiz.Web/Controllers/QuizController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Quiz.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Quiz.Web.Controllers
{
    [Authorize]
    public class QuizController : Controller
    {
        private readonly IQuizService quizService;
        private readonly IUserAnswerService userAnswerService;

        public QuizController(
            IQuizService quizService,
            IUserAnswerService userAnswerService)
        {
            this.quizService = quizService;
            this.userAnswerService = userAnswerService;
        }

        public IActionResult Test(int id)
        {
            this.quizService.StartQuiz(this.User?.Identity?.Name, id);
            var viewModel = this.quizService.GetQuizById(id);
            return this.View(viewModel);
        }

        public IActionResult Submit(int id)
        {
            foreach (var item in this.Request.Form)
            {
                var questionId = int.Parse(item.Key.Replace("q_", string.Empty));
                var answerId = int.Parse(item.Value);
                this.userAnswerService.AddUserAnswer(this.User.Identity.Name, questionId, answerId);
            }

            return this.RedirectToAction("Results", new { id });
        }

        public IActionResult Results(int id)
        {
            var points = this.userAnswerService
                .GetUserResult(this.User.Identity.Name, id);
            return this.View(points);
        }
    }
}

CSharp-DB/Databases-Advanced/Homeworks/WorkshopQuizSystem/Quiz.Web/Views/Home/Index.cshtml
@model IEnumerable<Quiz.Services.Models.UserQuizViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome!!!</h1>
    <p><a href="https://softuni.bg">SoftUni</a>.</p>
</div>

<table class="table table-sm table-striped table-hover table-bordered">
    <tr><th>Quiz name</th><th>Action</th></tr>
    @foreach (var quiz in Model)
    {
        <tr>
            <td>@quiz.Title</td>
            <td>
                @if (quiz.Status == Quiz.Services.Models.QuizStatus.NotStarted)
                {
                    <a asp-controller="Quiz" asp-action="Test" asp-route-id="@quiz.QuizId" class="btn btn-success">Start test</a>
                }
                else if (quiz.Status == Quiz.Services.Models.QuizStatus.InProgress)
                {
                    <a href="/Quiz/Test/@quiz.QuizId" class="btn btn-warning">Continue test</a>
                }
                else
                {
                    <a href="/Quiz/Results/@quiz.QuizId" class="btn btn-secondary">View results</a>
                }
            </td>
        </tr>
    }
</table>

CSharp-DB/Databases-Advanced/Homeworks/WorkshopQuizSystem/Quiz.Web/Views/Quiz/Results.cshtml
@model int
@{
    ViewData["Title"] = "Results";
}

<h1>Your points: @Model</h1>

CSharp-DB/Databases-Advanced/Homeworks/WorkshopQuizSystem/Quiz.Web/Views/Quiz/Test.cshtml
@using Quiz.Services.Models
@model QuizViewModel
@{
    ViewData["Title"] = "Test";
}

<h1>@Model.Title</h1>

<form action="/Quiz/Submit/@Model.Id" method="post">
    @foreach (var question in Model.Questions)
    {
        <h5>@question.Title</h5>
        @foreach (var answer in question.Answers)
        {
            <div>
                <input type="radio" name="q_@question.Id" value="@answer.Id" id="a_@answer.Id" />
                <label for="a_@answer.Id">@answer.Title</label>
            </div>
        }
    }
    <input type="submit" value="Send answers" class="btn btn-primary" />
</form>